#!/usr/bin/env python
# -*-coding:utf-8 -*-

#Author:HXJ



# age=25
# if age>20:
# 	print('Success')
# else:
# 	print('fail')
# print('success') if age>20 else print('fail')
# if age>15:print('正确')




# a=True
# if a:
# 	print('结果正确')
# else:
# 	print('结果错误')
# for i in range(0,10):
# 	print(i)

# while True:
# 	p=int(input('1.姓名 2.年龄\n'))
# 	if p==1:
# 		name=input('你的名字是:\n')
# 	elif p==2:
# 		age=input('你的年龄是:\n')
# 	else:
# 		break


# str1='admin'
# print(str1.replace('ad','baidu'))
# print(str1.find('m'))
# print(str1.startswith('d'))
# print(str1.isdigit())
# print(str1.upper())
# print(str1.lower())
# print(str1.split('m'))
# print('m '.join(str1.split('m ')))
# print(str1)

# name='yoya'
# age=18
# print('我的名字是%s,我今年是%s岁'%(name,age))
# print('我的名字是{0},我今年是{1}岁'.format(age,name))
# print('我的名字是{name},我今年是{age}岁'.format(age=age,name=name))

# list1=[1,99,23,45,667,1223,4]
# list3=[2,3,4]
# name=(dir(list1))
# print(name)
# list1.append(999)
# list1.insert(1,999)
# list2=list1.copy()
# print(list1.index(1))
# list1.extend(list3)
# print(list1.pop())
# print(list1)
# list1.reverse()
# print(list1)
# list1.sort()
# print(list1)
# for i in list1:
# 	if i>2:
# 		print(i)
# print([x+1 for x in list1])
# print([x+1 for x in list1 if x>100])

# tuple1=(1,5,6,['hxj','18'],{'name':'name','age':18})
# print(dir(tuple1))
# tuple1[3][0]='admin'
# tuple1[4]['name']='hxj'
# print(tuple1)

# dict1={'name':'hxj','age':18}
# print(dir(dict1))
# dict2=dict1.copy()
# dict1ct1.clear()
# print(dict1.get('age'))
# print(dict2)
# print(dict1)

# for key in dict1.keys():
# 	print(key)
# for value in dict1.values():
# 	print(value)
# for key,value in dict1.items():
# 	print(key,':',value)
# dict2={'address':'chengdu'}
# dict1.update(dict2)
# print(dict1)
# print(sorted(dict1.items(),key=lambda item:item[0]))
# 拉勾网
dict1={
	"success": True,
	"msg": None,
	"code": 0,
	"content": {
		"showId": "5f40639d071340c889aba74e2ae9dff1",
		"hrInfoMap": {
			"6662212": {
				"userId": 9687871,
				"portrait": "i/image3/M00/03/D6/CgpOIFpdsMqAEKu_AACzFJD-5po347.jpg",
				"realName": "Liam Lu",
				"positionName": "招聘主管",
				"phone": None,
				"receiveEmail": None,
				"userLevel": "G1",
				"canTalk": True
			},
			"7076070": {
				"userId": 9641903,
				"portrait": "i/image/M00/5C/A3/Ciqc1F-Cm4mAY1bnAAB1FSDKz5k681.jpg",
				"realName": "首席人才官",
				"positionName": "",
				"phone": None,
				"receiveEmail": None,
				"userLevel": "G1",
				"canTalk": True
			},
			"7227677": {
				"userId": 294593,
				"portrait": "i/image2/M01/A4/BF/CgotOVvb9fSACLUDAAAiPkSuMyw228.jpg",
				"realName": "zane",
				"positionName": "",
				"phone": None,
				"receiveEmail": None,
				"userLevel": "G1",
				"canTalk": True
			},
			"7814194": {
				"userId": 343231,
				"portrait": None,
				"realName": "维信招聘",
				"positionName": "招聘经理",
				"phone": None,
				"receiveEmail": None,
				"userLevel": "G1",
				"canTalk": True
			},
			"7852238": {
				"userId": 5932517,
				"portrait": "i/image2/M01/19/58/CgotOVyw0YaAXq7kAABq7l7a11A487.png",
				"realName": "三七互娱HR",
				"positionName": "HR",
				"phone": None,
				"receiveEmail": None,
				"userLevel": "G1",
				"canTalk": True
			},
			"7887909": {
				"userId": 16639146,
				"portrait": "i/image2/M01/0E/AC/CgotOVyhgdKAWLwZAACHltqNgkc507.png",
				"realName": "何静",
				"positionName": "HR",
				"phone": None,
				"receiveEmail": None,
				"userLevel": "G1",
				"canTalk": True
			},
			"7892659": {
				"userId": 21185150,
				"portrait": "i/image2/M01/0E/AC/CgotOVyhgc2AU_p3AABtO4vAHkg858.png",
				"realName": "赵瑜",
				"positionName": "人力资源经理",
				"phone": None,
				"receiveEmail": None,
				"userLevel": "G1",
				"canTalk": True
			},
			"8031678": {
				"userId": 1707653,
				"portrait": "i/image2/M01/AC/58/CgoB5l3alJCADji7AAB8tpoFtiw724.png",
				"realName": "HR",
				"positionName": "HR",
				"phone": None,
				"receiveEmail": None,
				"userLevel": "G1",
				"canTalk": True
			},
			"8160620": {
				"userId": 294593,
				"portrait": "i/image2/M01/A4/BF/CgotOVvb9fSACLUDAAAiPkSuMyw228.jpg",
				"realName": "zane",
				"positionName": "",
				"phone": None,
				"receiveEmail": None,
				"userLevel": "G1",
				"canTalk": True
			},
			"8353774": {
				"userId": 14369019,
				"portrait": "i/image2/M01/57/FF/CgotOV0cYBSANeGyAADTzNMUBkM637.png",
				"realName": "程嫣",
				"positionName": "人事经理",
				"phone": None,
				"receiveEmail": None,
				"userLevel": "G1",
				"canTalk": True
			},
			"8387815": {
				"userId": 5104512,
				"portrait": "i/image2/M01/22/C7/CgoB5lzAdRGAGWvoAAB_OabcIyE480.png",
				"realName": "tracy",
				"positionName": "hr",
				"phone": None,
				"receiveEmail": None,
				"userLevel": "G1",
				"canTalk": True
			},
			"8429193": {
				"userId": 8558408,
				"portrait": "i/image2/M01/6A/1C/CgotOVtJoMiABi3WAAD390S2gzs512.png",
				"realName": "yangli",
				"positionName": "HR",
				"phone": None,
				"receiveEmail": None,
				"userLevel": "G1",
				"canTalk": True
			},
			"8429236": {
				"userId": 8391374,
				"portrait": "i/image3/M01/6D/52/CgpOIF5dHfmAIhbLAAAa5aafbcQ85.jpeg",
				"realName": "张女士",
				"positionName": "hrbp",
				"phone": None,
				"receiveEmail": None,
				"userLevel": "G1",
				"canTalk": True
			},
			"8536215": {
				"userId": 20617580,
				"portrait": "i/image2/M01/0E/AC/CgotOVyhgc2AU_p3AABtO4vAHkg858.png",
				"realName": "毛利莉",
				"positionName": "招聘专员",
				"phone": None,
				"receiveEmail": None,
				"userLevel": "G1",
				"canTalk": True
			},
			"8542966": {
				"userId": 13115499,
				"portrait": "i/image2/M01/21/62/CgoB5ly-rNGAISzSAABG1Ej4DyU278.png",
				"realName": "lexi",
				"positionName": "行政人事 人力资源",
				"phone": None,
				"receiveEmail": None,
				"userLevel": "G1",
				"canTalk": True
			}
		},
		"pageNo": 1,
		"positionResult": {
			"resultSize": 15,
			"result": [
				{
					"positionId": 7887909,
					"positionName": "运维工程师",
					"companyId": 117868860,
					"companyFullName": "宁波中茂网络科技有限公司杭州分公司",
					"companyShortName": "富通天下",
					"companyLogo": "i/image3/M01/01/C6/Ciqah155zuqALFd2AABUgz0I7Mk279.png",
					"companySize": "150-500人",
					"industryField": "软件服务｜咨询,营销服务｜咨询",
					"financeStage": "不需要融资",
					"companyLabelList": [
						"绩效奖金",
						"带薪年假",
						"节日礼物",
						"技能培训"
					],
					"firstType": "开发|测试|运维类",
					"secondType": "运维",
					"thirdType": "运维工程师",
					"skillLables": [
						"Shell",
						"Linux",
						"Python",
						"MySQL"
					],
					"positionLables": [
						"Shell",
						"Linux",
						"Python",
						"MySQL"
					],
					"industryLables": [],
					"createTime": "2021-04-05 13:00:53",
					"formatCreateTime": "13:00发布",
					"city": "杭州",
					"district": "拱墅区",
					"businessZones": None,
					"salary": "8k-15k",
					"salaryMonth": "0",
					"workYear": "3-5年",
					"jobNature": "全职",
					"education": "大专",
					"positionAdvantage": "发展前景，稳定性高",
					"imState": "threeDays",
					"lastLogin": "2021-04-02 19:32:53",
					"publisherId": 16639146,
					"approve": 1,
					"subwayline": None,
					"stationname": None,
					"linestaion": None,
					"latitude": "30.336239",
					"longitude": "120.113287",
					"distance": None,
					"hitags": None,
					"resumeProcessRate": 50,
					"resumeProcessDay": 1,
					"score": 55,
					"newScore": 0,
					"matchScore": 3.6036634,
					"matchScoreExplain": None,
					"query": None,
					"explain": None,
					"isSchoolJob": 0,
					"adWord": 0,
					"plus": None,
					"pcShow": 0,
					"appShow": 0,
					"deliver": 0,
					"gradeDescription": None,
					"promotionScoreExplain": None,
					"isHotHire": 0,
					"count": 0,
					"aggregatePositionIds": [],
					"reCallType": None,
					"userExpectId": -1,
					"userExpectText": "",
					"promotionType": None,
					"is51Job": False,
					"expectJobId": None,
					"encryptId": "1f07cd8df73d64f26652d16336f4fd65c9763cb8945eaebdef6f5f21ef9ce1ef",
					"detailRecall": False,
					"famousCompany": False,
					"hunterJob": False
				},
				{
					"positionId": 7852238,
					"positionName": "高级运维开发工程师",
					"companyId": 658,
					"companyFullName": "广州三七互娱科技有限公司",
					"companyShortName": "三七互娱",
					"companyLogo": "i/image2/M01/37/BC/CgoB5lzmTciATaZZAAHQFegVPBE112.png",
					"companySize": "2000人以上",
					"industryField": "游戏",
					"financeStage": "上市公司",
					"companyLabelList": [
						"高额奖金",
						"快速晋升",
						"带薪年假",
						"节日礼物"
					],
					"firstType": "开发|测试|运维类",
					"secondType": "运维",
					"thirdType": "运维开发工程师",
					"skillLables": [
						"Python",
						"Shell",
						"DevOps/AIOps"
					],
					"positionLables": [
						"Python",
						"Shell",
						"DevOps/AIOps"
					],
					"industryLables": [],
					"createTime": "2021-04-01 19:40:04",
					"formatCreateTime": "2021-04-01",
					"city": "广州",
					"district": "天河区",
					"businessZones": [
						"车陂"
					],
					"salary": "20k-30k",
					"salaryMonth": "15",
					"workYear": "5-10年",
					"jobNature": "全职",
					"education": "本科",
					"positionAdvantage": "上市公司，优厚福利待遇",
					"imState": "threeDays",
					"lastLogin": "2021-04-02 15:26:33",
					"publisherId": 5932517,
					"approve": 1,
					"subwayline": "5号线",
					"stationname": "车陂南",
					"linestaion": "4号线_车陂;4号线_车陂南;5号线_科韵路;5号线_车陂南",
					"latitude": "23.116982",
					"longitude": "113.383947",
					"distance": None,
					"hitags": None,
					"resumeProcessRate": 47,
					"resumeProcessDay": 1,
					"score": 40,
					"newScore": 0,
					"matchScore": 1.4502696,
					"matchScoreExplain": None,
					"query": None,
					"explain": None,
					"isSchoolJob": 0,
					"adWord": 0,
					"plus": None,
					"pcShow": 0,
					"appShow": 0,
					"deliver": 0,
					"gradeDescription": None,
					"promotionScoreExplain": None,
					"isHotHire": 0,
					"count": 0,
					"aggregatePositionIds": [],
					"reCallType": None,
					"userExpectId": -1,
					"userExpectText": "",
					"promotionType": None,
					"is51Job": False,
					"expectJobId": None,
					"encryptId": "a74f564dd9fb69861ab013cd1b332b9c",
					"detailRecall": False,
					"famousCompany": True,
					"hunterJob": False
				},
				{
					"positionId": 7076070,
					"positionName": "运维开发工程师",
					"companyId": 286431,
					"companyFullName": "爱客科技（深圳）有限公司",
					"companyShortName": "爱客科技 AfterShip",
					"companyLogo": "i/image2/M01/A3/E0/CgotOV2_33OAJMbDAAAoozKUaSQ386.png",
					"companySize": "150-500人",
					"industryField": "软件服务｜咨询,营销服务｜咨询,数据服务｜咨询",
					"financeStage": "不需要融资",
					"companyLabelList": [
						"持续盈利",
						"国际龙头企业",
						"SaaS平台",
						"极客氛围"
					],
					"firstType": "开发|测试|运维类",
					"secondType": "运维",
					"thirdType": "运维开发工程师",
					"skillLables": [
						"配置管理"
					],
					"positionLables": [
						"配置管理"
					],
					"industryLables": [],
					"createTime": "2021-04-05 13:05:26",
					"formatCreateTime": "13:05发布",
					"city": "深圳",
					"district": "南山区",
					"businessZones": None,
					"salary": "20k-30k",
					"salaryMonth": "14",
					"workYear": "3-5年",
					"jobNature": "全职",
					"education": "本科",
					"positionAdvantage": "海外SAAS 极客氛围 敏捷开发",
					"imState": "today",
					"lastLogin": "2021-04-05 13:02:44",
					"publisherId": 9641903,
					"approve": 1,
					"subwayline": "2号线/蛇口线",
					"stationname": "高新园",
					"linestaion": "1号线/罗宝线_高新园;1号线/罗宝线_深大;2号线/蛇口线_科苑",
					"latitude": "22.535004",
					"longitude": "113.941975",
					"distance": None,
					"hitags": None,
					"resumeProcessRate": 100,
					"resumeProcessDay": 1,
					"score": 34,
					"newScore": 0,
					"matchScore": 5.058154,
					"matchScoreExplain": None,
					"query": None,
					"explain": None,
					"isSchoolJob": 0,
					"adWord": 0,
					"plus": None,
					"pcShow": 0,
					"appShow": 0,
					"deliver": 0,
					"gradeDescription": None,
					"promotionScoreExplain": None,
					"isHotHire": 0,
					"count": 0,
					"aggregatePositionIds": [],
					"reCallType": None,
					"userExpectId": -1,
					"userExpectText": "",
					"promotionType": None,
					"is51Job": False,
					"expectJobId": None,
					"encryptId": "b590864cd75a53eefdd6c848bdd2c608b2fc0fa008aca901",
					"detailRecall": False,
					"famousCompany": False,
					"hunterJob": False
				},
				{
					"positionId": 7892659,
					"positionName": "运维工程师",
					"companyId": 159576,
					"companyFullName": "迈泺（上海）信息科技有限公司",
					"companyShortName": "迈泺信息",
					"companyLogo": "i/image6/M01/29/53/CioPOWBhMCuATmrIAAAKVhJguDM236.jpg",
					"companySize": "50-150人",
					"industryField": "数据服务｜咨询,科技金融",
					"financeStage": "A轮",
					"companyLabelList": [],
					"firstType": "开发|测试|运维类",
					"secondType": "运维",
					"thirdType": "运维工程师",
					"skillLables": [
						"MySQL"
					],
					"positionLables": [
						"MySQL"
					],
					"industryLables": [],
					"createTime": "2021-04-05 13:12:37",
					"formatCreateTime": "13:12发布",
					"city": "上海",
					"district": "普陀区",
					"businessZones": [
						"长风公园"
					],
					"salary": "8k-15k",
					"salaryMonth": "0",
					"workYear": "3-5年",
					"jobNature": "全职",
					"education": "本科",
					"positionAdvantage": "扁平管理",
					"imState": "today",
					"lastLogin": "2021-04-05 13:11:11",
					"publisherId": 21185150,
					"approve": 1,
					"subwayline": "2号线",
					"stationname": "威宁路",
					"linestaion": "2号线_娄山关路;2号线_威宁路;13号线_大渡河路",
					"latitude": "31.221338",
					"longitude": "121.394965",
					"distance": None,
					"hitags": None,
					"resumeProcessRate": 0,
					"resumeProcessDay": 0,
					"score": 27,
					"newScore": 0,
					"matchScore": 5.0870996,
					"matchScoreExplain": None,
					"query": None,
					"explain": None,
					"isSchoolJob": 0,
					"adWord": 0,
					"plus": None,
					"pcShow": 0,
					"appShow": 0,
					"deliver": 0,
					"gradeDescription": None,
					"promotionScoreExplain": None,
					"isHotHire": 0,
					"count": 0,
					"aggregatePositionIds": [],
					"reCallType": None,
					"userExpectId": -1,
					"userExpectText": "",
					"promotionType": None,
					"is51Job": False,
					"expectJobId": None,
					"encryptId": "fd6efbe9c09c5dd5c9b554742d9b4b5446ca7d459ff724c6",
					"detailRecall": False,
					"famousCompany": False,
					"hunterJob": False
				},
				{
					"positionId": 8542966,
					"positionName": "系统运维工程师",
					"companyId": 323861,
					"companyFullName": "上海宇辰科技发展有限公司",
					"companyShortName": "宇辰科技",
					"companyLogo": "i/image2/M01/04/80/CgoB5lyTWEGAAaJVAABG1Ej4DyU599.png",
					"companySize": "50-150人",
					"industryField": "数据服务,硬件",
					"financeStage": "未融资",
					"companyLabelList": [
						"午餐补助",
						"通讯津贴",
						"定期体检",
						"带薪年假"
					],
					"firstType": "开发|测试|运维类",
					"secondType": "运维",
					"thirdType": "运维工程师",
					"skillLables": [
						"Linux",
						"windows",
						"vmware"
					],
					"positionLables": [
						"Linux",
						"windows",
						"vmware"
					],
					"industryLables": [],
					"createTime": "2021-04-05 13:18:17",
					"formatCreateTime": "13:18发布",
					"city": "上海",
					"district": "普陀区",
					"businessZones": None,
					"salary": "9k-12k",
					"salaryMonth": "13",
					"workYear": "1-3年",
					"jobNature": "全职",
					"education": "大专",
					"positionAdvantage": "周末双休 30+技术团队",
					"imState": "threeDays",
					"lastLogin": "2021-04-05 13:18:14",
					"publisherId": 13115499,
					"approve": 1,
					"subwayline": "3号线",
					"stationname": "岚皋路",
					"linestaion": "3号线_镇坪路;4号线_镇坪路;7号线_镇坪路;7号线_岚皋路;7号线_新村路;11号线_真如;11号线_真如",
					"latitude": "31.25495",
					"longitude": "121.419225",
					"distance": None,
					"hitags": None,
					"resumeProcessRate": 38,
					"resumeProcessDay": 1,
					"score": 26,
					"newScore": 0,
					"matchScore": 4.877248,
					"matchScoreExplain": None,
					"query": None,
					"explain": None,
					"isSchoolJob": 0,
					"adWord": 0,
					"plus": None,
					"pcShow": 0,
					"appShow": 0,
					"deliver": 0,
					"gradeDescription": None,
					"promotionScoreExplain": None,
					"isHotHire": 0,
					"count": 0,
					"aggregatePositionIds": [],
					"reCallType": None,
					"userExpectId": -1,
					"userExpectText": "",
					"promotionType": None,
					"is51Job": False,
					"expectJobId": None,
					"encryptId": "f82d059ab954cd1f51929e72b3526bfbf502443c3237daf3",
					"detailRecall": False,
					"famousCompany": False,
					"hunterJob": False
				},
				{
					"positionId": 8536215,
					"positionName": "运维工程师",
					"companyId": 128998,
					"companyFullName": "上海海万信息科技股份有限公司",
					"companyShortName": "海万科技",
					"companyLogo": "i/image/M00/2A/A6/Cgp3O1cyziuAfM5AAAAe20ZOb-4754.png",
					"companySize": "500-2000人",
					"industryField": "软件服务｜咨询,IT技术服务｜咨询",
					"financeStage": "不需要融资",
					"companyLabelList": [],
					"firstType": "开发|测试|运维类",
					"secondType": "运维",
					"thirdType": "运维工程师",
					"skillLables": [
						"Linux",
						"SQL",
						"CPU命令"
					],
					"positionLables": [
						"Linux",
						"SQL",
						"CPU命令"
					],
					"industryLables": [],
					"createTime": "2021-04-05 13:22:37",
					"formatCreateTime": "13:22发布",
					"city": "上海",
					"district": "徐汇区",
					"businessZones": None,
					"salary": "9k-13k",
					"salaryMonth": "0",
					"workYear": "1-3年",
					"jobNature": "全职",
					"education": "本科",
					"positionAdvantage": "500强企业项目 薪资福利好 反馈快",
					"imState": "today",
					"lastLogin": "2021-04-05 13:22:31",
					"publisherId": 20617580,
					"approve": 1,
					"subwayline": "7号线",
					"stationname": "东安路",
					"linestaion": "4号线_大木桥路;4号线_东安路;4号线_上海体育场;7号线_龙华中路;7号线_东安路;11号线_龙华;11号线_龙华;12号线_龙华;12号线_龙华中路;12号线_大木桥路",
					"latitude": "31.182967",
					"longitude": "121.456433",
					"distance": None,
					"hitags": None,
					"resumeProcessRate": 12,
					"resumeProcessDay": 1,
					"score": 25,
					"newScore": 0,
					"matchScore": 5.050918,
					"matchScoreExplain": None,
					"query": None,
					"explain": None,
					"isSchoolJob": 0,
					"adWord": 0,
					"plus": None,
					"pcShow": 0,
					"appShow": 0,
					"deliver": 0,
					"gradeDescription": None,
					"promotionScoreExplain": None,
					"isHotHire": 0,
					"count": 0,
					"aggregatePositionIds": [],
					"reCallType": None,
					"userExpectId": -1,
					"userExpectText": "",
					"promotionType": None,
					"is51Job": False,
					"expectJobId": None,
					"encryptId": "d71b9c7ca4d0a0040ad8ffe97d5c518d62bf934b0659b0ec",
					"detailRecall": False,
					"famousCompany": False,
					"hunterJob": False
				},
				{
					"positionId": 8429193,
					"positionName": "大数据运维工程师",
					"companyId": 62,
					"companyFullName": "北京字节跳动网络技术有限公司",
					"companyShortName": "字节跳动",
					"companyLogo": "i/image2/M01/79/0A/CgoB5ltr2A-AM5SFAADbT9jQCn841.jpeg",
					"companySize": "2000人以上",
					"industryField": "内容资讯,短视频",
					"financeStage": "D轮及以上",
					"companyLabelList": [
						"扁平管理",
						"弹性工作",
						"就近租房补贴",
						"六险一金"
					],
					"firstType": "开发|测试|运维类",
					"secondType": "运维",
					"thirdType": "其他运维",
					"skillLables": [
						"运维"
					],
					"positionLables": [
						"运维"
					],
					"industryLables": [],
					"createTime": "2021-04-05 05:40:59",
					"formatCreateTime": "05:40发布",
					"city": "成都",
					"district": "武侯区",
					"businessZones": None,
					"salary": "20k-40k",
					"salaryMonth": "0",
					"workYear": "不限",
					"jobNature": "全职",
					"education": "本科",
					"positionAdvantage": "六险一金,股票期权,团队氛围好",
					"imState": "threeDays",
					"lastLogin": "2021-04-03 18:12:07",
					"publisherId": 8558408,
					"approve": 1,
					"subwayline": "1号线(五根松)",
					"stationname": "天府五街",
					"linestaion": "1号线(五根松)_天府五街;1号线(五根松)_天府三街;1号线(五根松)_世纪城;1号线(科学城)_天府五街;1号线(科学城)_天府三街;1号线(科学城)_世纪城",
					"latitude": "30.543203",
					"longitude": "104.064309",
					"distance": None,
					"hitags": None,
					"resumeProcessRate": 0,
					"resumeProcessDay": 1,
					"score": 24,
					"newScore": 0,
					"matchScore": 3.480647,
					"matchScoreExplain": None,
					"query": None,
					"explain": None,
					"isSchoolJob": 0,
					"adWord": 0,
					"plus": None,
					"pcShow": 0,
					"appShow": 0,
					"deliver": 0,
					"gradeDescription": None,
					"promotionScoreExplain": None,
					"isHotHire": 0,
					"count": 0,
					"aggregatePositionIds": [],
					"reCallType": None,
					"userExpectId": -1,
					"userExpectText": "",
					"promotionType": None,
					"is51Job": False,
					"expectJobId": None,
					"encryptId": "9fddcab57c5a4d7db100b030672d1cce",
					"detailRecall": False,
					"famousCompany": True,
					"hunterJob": False
				},
				{
					"positionId": 7814194,
					"positionName": "高级运维工程师",
					"companyId": 27155,
					"companyFullName": "上海维信荟智金融科技有限公司",
					"companyShortName": "维信金科",
					"companyLogo": "i/image/M00/52/D5/CgpEMll2nn2APNPVAAAOYVihp4s239.jpg",
					"companySize": "2000人以上",
					"industryField": "科技金融",
					"financeStage": "上市公司",
					"companyLabelList": [
						"技能培训",
						"节日礼物",
						"年底双薪",
						"带薪年假"
					],
					"firstType": "开发|测试|运维类",
					"secondType": "运维",
					"thirdType": "运维工程师",
					"skillLables": [
						"应用运维",
						"K8s/Docker",
						"DevOps/AIOps",
						"Linux"
					],
					"positionLables": [
						"应用运维",
						"K8s/Docker",
						"DevOps/AIOps",
						"Linux"
					],
					"industryLables": [],
					"createTime": "2021-04-05 13:00:18",
					"formatCreateTime": "13:00发布",
					"city": "上海",
					"district": "虹口区",
					"businessZones": [
						"北外滩"
					],
					"salary": "15k-25k",
					"salaryMonth": "0",
					"workYear": "3-5年",
					"jobNature": "全职",
					"education": "本科",
					"positionAdvantage": "周末双休 扁平化管理 团队氛围佳",
					"imState": "threeDays",
					"lastLogin": "2021-04-02 13:32:02",
					"publisherId": 343231,
					"approve": 1,
					"subwayline": "3号线",
					"stationname": "天潼路",
					"linestaion": "2号线_南京东路;3号线_宝山路;4号线_宝山路;10号线_四川北路;10号线_天潼路;10号线_南京东路;10号线_四川北路;10号线_天潼路;10号线_南京东路;12号线_天潼路;12号线_国际客运中心",
					"latitude": "31.245606",
					"longitude": "121.487757",
					"distance": None,
					"hitags": None,
					"resumeProcessRate": 0,
					"resumeProcessDay": 0,
					"score": 23,
					"newScore": 0,
					"matchScore": 3.6000454,
					"matchScoreExplain": None,
					"query": None,
					"explain": None,
					"isSchoolJob": 0,
					"adWord": 0,
					"plus": None,
					"pcShow": 0,
					"appShow": 0,
					"deliver": 0,
					"gradeDescription": None,
					"promotionScoreExplain": None,
					"isHotHire": 0,
					"count": 0,
					"aggregatePositionIds": [],
					"reCallType": None,
					"userExpectId": -1,
					"userExpectText": "",
					"promotionType": None,
					"is51Job": False,
					"expectJobId": None,
					"encryptId": "43794adba583b192c6899452abd54864fdcb20325aad3705",
					"detailRecall": False,
					"famousCompany": False,
					"hunterJob": False
				},
				{
					"positionId": 7227677,
					"positionName": "运维开发工程师",
					"companyId": 147,
					"companyFullName": "北京拉勾网络技术有限公司",
					"companyShortName": "拉勾网",
					"companyLogo": "i/image2/M01/79/70/CgotOV1aS4qAWK6WAAAM4NTpXws809.png",
					"companySize": "500-2000人",
					"industryField": "工具类产品,在线教育",
					"financeStage": "D轮及以上",
					"companyLabelList": [
						"五险一金",
						"弹性工作",
						"带薪年假",
						"免费两餐"
					],
					"firstType": "开发|测试|运维类",
					"secondType": "运维",
					"thirdType": "运维开发工程师",
					"skillLables": [
						"运维开发"
					],
					"positionLables": [
						"运维开发"
					],
					"industryLables": [],
					"createTime": "2021-04-02 09:51:11",
					"formatCreateTime": "3天前发布",
					"city": "北京",
					"district": "海淀区",
					"businessZones": [
						"中关村",
						"万泉河",
						"苏州街"
					],
					"salary": "15k-30k",
					"salaryMonth": "0",
					"workYear": "3-5年",
					"jobNature": "全职",
					"education": "本科",
					"positionAdvantage": "福利待遇好，周末双休，发展空间大",
					"imState": "threeDays",
					"lastLogin": "2021-04-02 22:37:58",
					"publisherId": 294593,
					"approve": 1,
					"subwayline": "10号线",
					"stationname": "中关村",
					"linestaion": "4号线大兴线_海淀黄庄;4号线大兴线_中关村;4号线大兴线_北京大学东门;10号线_苏州街;10号线_海淀黄庄",
					"latitude": "39.984752",
					"longitude": "116.30679",
					"distance": None,
					"hitags": [
						"免费下午茶",
						"ipo倒计时",
						"bat背景",
						"地铁周边",
						"每天管两餐",
						"定期团建",
						"团队年轻有活力",
						"6险1金"
					],
					"resumeProcessRate": 67,
					"resumeProcessDay": 1,
					"score": 22,
					"newScore": 0,
					"matchScore": 3.480647,
					"matchScoreExplain": None,
					"query": None,
					"explain": None,
					"isSchoolJob": 0,
					"adWord": 0,
					"plus": None,
					"pcShow": 0,
					"appShow": 0,
					"deliver": 0,
					"gradeDescription": None,
					"promotionScoreExplain": None,
					"isHotHire": 0,
					"count": 0,
					"aggregatePositionIds": [],
					"reCallType": None,
					"userExpectId": -1,
					"userExpectText": "",
					"promotionType": None,
					"is51Job": False,
					"expectJobId": None,
					"encryptId": "c3ae6314770f6995d27368908dee0576",
					"detailRecall": False,
					"famousCompany": True,
					"hunterJob": False
				},
				{
					"positionId": 8160620,
					"positionName": "运维工程师",
					"companyId": 147,
					"companyFullName": "北京拉勾网络技术有限公司",
					"companyShortName": "拉勾网",
					"companyLogo": "i/image2/M01/79/70/CgotOV1aS4qAWK6WAAAM4NTpXws809.png",
					"companySize": "500-2000人",
					"industryField": "工具类产品,在线教育",
					"financeStage": "D轮及以上",
					"companyLabelList": [
						"五险一金",
						"弹性工作",
						"带薪年假",
						"免费两餐"
					],
					"firstType": "开发|测试|运维类",
					"secondType": "运维",
					"thirdType": "运维工程师",
					"skillLables": [
						"DevOps/AIOps",
						"K8s/Docker",
						"CI/CD"
					],
					"positionLables": [
						"DevOps/AIOps",
						"K8s/Docker",
						"CI/CD"
					],
					"industryLables": [],
					"createTime": "2021-04-02 09:51:11",
					"formatCreateTime": "3天前发布",
					"city": "北京",
					"district": "海淀区",
					"businessZones": [
						"中关村",
						"万泉河",
						"苏州街"
					],
					"salary": "20k-40k",
					"salaryMonth": "0",
					"workYear": "5-10年",
					"jobNature": "全职",
					"education": "本科",
					"positionAdvantage": "福利待遇好，周末双休，发展空间大",
					"imState": "threeDays",
					"lastLogin": "2021-04-02 22:37:58",
					"publisherId": 294593,
					"approve": 1,
					"subwayline": "10号线",
					"stationname": "中关村",
					"linestaion": "4号线大兴线_海淀黄庄;4号线大兴线_中关村;4号线大兴线_北京大学东门;10号线_苏州街;10号线_海淀黄庄",
					"latitude": "39.982151",
					"longitude": "116.307958",
					"distance": None,
					"hitags": [
						"免费下午茶",
						"ipo倒计时",
						"bat背景",
						"地铁周边",
						"每天管两餐",
						"定期团建",
						"团队年轻有活力",
						"6险1金"
					],
					"resumeProcessRate": 67,
					"resumeProcessDay": 1,
					"score": 22,
					"newScore": 0,
					"matchScore": 3.480647,
					"matchScoreExplain": None,
					"query": None,
					"explain": None,
					"isSchoolJob": 0,
					"adWord": 0,
					"plus": None,
					"pcShow": 0,
					"appShow": 0,
					"deliver": 0,
					"gradeDescription": None,
					"promotionScoreExplain": None,
					"isHotHire": 0,
					"count": 0,
					"aggregatePositionIds": [],
					"reCallType": None,
					"userExpectId": -1,
					"userExpectText": "",
					"promotionType": None,
					"is51Job": False,
					"expectJobId": None,
					"encryptId": "babb55799cfd8a4d5a08d7b6a8cffad6",
					"detailRecall": False,
					"famousCompany": True,
					"hunterJob": False
				},
				{
					"positionId": 8429236,
					"positionName": "运维开发工程师",
					"companyId": 62,
					"companyFullName": "北京字节跳动网络技术有限公司",
					"companyShortName": "字节跳动",
					"companyLogo": "i/image2/M01/79/0A/CgoB5ltr2A-AM5SFAADbT9jQCn841.jpeg",
					"companySize": "2000人以上",
					"industryField": "内容资讯,短视频",
					"financeStage": "D轮及以上",
					"companyLabelList": [
						"扁平管理",
						"弹性工作",
						"就近租房补贴",
						"六险一金"
					],
					"firstType": "开发|测试|运维类",
					"secondType": "运维",
					"thirdType": "运维工程师",
					"skillLables": [],
					"positionLables": [
						"后端开发"
					],
					"industryLables": [
						"后端开发"
					],
					"createTime": "2021-04-05 05:41:05",
					"formatCreateTime": "05:41发布",
					"city": "深圳",
					"district": "南山区",
					"businessZones": None,
					"salary": "20k-40k",
					"salaryMonth": "0",
					"workYear": "不限",
					"jobNature": "全职",
					"education": "本科",
					"positionAdvantage": "下午茶,六险一金,免费三餐,弹性工作",
					"imState": "threeDays",
					"lastLogin": "2021-04-02 16:06:42",
					"publisherId": 8391374,
					"approve": 1,
					"subwayline": "2号线/蛇口线",
					"stationname": "南山",
					"linestaion": "2号线/蛇口线_登良;11号线/机场线_南山",
					"latitude": "22.515508",
					"longitude": "113.925129",
					"distance": None,
					"hitags": None,
					"resumeProcessRate": 0,
					"resumeProcessDay": 0,
					"score": 22,
					"newScore": 0,
					"matchScore": 3.480647,
					"matchScoreExplain": None,
					"query": None,
					"explain": None,
					"isSchoolJob": 0,
					"adWord": 0,
					"plus": None,
					"pcShow": 0,
					"appShow": 0,
					"deliver": 0,
					"gradeDescription": None,
					"promotionScoreExplain": None,
					"isHotHire": 0,
					"count": 0,
					"aggregatePositionIds": [],
					"reCallType": None,
					"userExpectId": -1,
					"userExpectText": "",
					"promotionType": None,
					"is51Job": False,
					"expectJobId": None,
					"encryptId": "7ef60904d7fc4a90915b1efa9ed4d61f",
					"detailRecall": False,
					"famousCompany": True,
					"hunterJob": False
				},
				{
					"positionId": 8353774,
					"positionName": "系统运维工程师",
					"companyId": 738678,
					"companyFullName": "武汉鹰歌网络科技有限公司",
					"companyShortName": "鹰歌游戏",
					"companyLogo": "i/image2/M01/58/EE/CgoB5l0dvfCAQS3iAADT6so7AMc390.png",
					"companySize": "15-50人",
					"industryField": "游戏",
					"financeStage": "天使轮",
					"companyLabelList": [],
					"firstType": "开发|测试|运维类",
					"secondType": "运维",
					"thirdType": "运维工程师",
					"skillLables": [
						"系统运维"
					],
					"positionLables": [
						"游戏",
						"系统运维"
					],
					"industryLables": [
						"游戏",
						"系统运维"
					],
					"createTime": "2021-04-05 13:24:07",
					"formatCreateTime": "13:24发布",
					"city": "武汉",
					"district": "洪山区",
					"businessZones": [
						"光谷"
					],
					"salary": "6k-10k",
					"salaryMonth": "13",
					"workYear": "1-3年",
					"jobNature": "全职",
					"education": "大专",
					"positionAdvantage": "项目奖金",
					"imState": "threeDays",
					"lastLogin": "2021-04-05 13:23:41",
					"publisherId": 14369019,
					"approve": 1,
					"subwayline": "2号线",
					"stationname": "光谷火车站",
					"linestaion": "2号线_黄龙山路;2号线_光谷火车站",
					"latitude": "30.484297",
					"longitude": "114.422465",
					"distance": None,
					"hitags": None,
					"resumeProcessRate": 50,
					"resumeProcessDay": 1,
					"score": 21,
					"newScore": 0,
					"matchScore": 4.978555,
					"matchScoreExplain": None,
					"query": None,
					"explain": None,
					"isSchoolJob": 0,
					"adWord": 0,
					"plus": None,
					"pcShow": 0,
					"appShow": 0,
					"deliver": 0,
					"gradeDescription": None,
					"promotionScoreExplain": None,
					"isHotHire": 0,
					"count": 0,
					"aggregatePositionIds": [],
					"reCallType": None,
					"userExpectId": -1,
					"userExpectText": "",
					"promotionType": None,
					"is51Job": False,
					"expectJobId": None,
					"encryptId": "5c57191f9bc406f32c6b9402559616b6cc96af8f39cb6625",
					"detailRecall": False,
					"famousCompany": False,
					"hunterJob": False
				},
				{
					"positionId": 8387815,
					"positionName": "高级运维工程师",
					"companyId": 129103,
					"companyFullName": "上海金亥通信设备有限公司",
					"companyShortName": "上海金亥",
					"companyLogo": "i/image/M00/2A/A7/Cgp3O1cyz1KAZEuVAAAWu4CQil8282.png",
					"companySize": "50-150人",
					"industryField": "网络通信",
					"financeStage": "不需要融资",
					"companyLabelList": [
						"定期体检",
						"带薪年假",
						"年底双薪",
						"免费班车"
					],
					"firstType": "开发|测试|运维类",
					"secondType": "运维",
					"thirdType": "运维工程师",
					"skillLables": [
						"系统运维",
						"自动化运维"
					],
					"positionLables": [
						"系统运维",
						"自动化运维"
					],
					"industryLables": [],
					"createTime": "2021-04-05 13:02:23",
					"formatCreateTime": "13:02发布",
					"city": "上海",
					"district": "浦东新区",
					"businessZones": None,
					"salary": "14k-20k",
					"salaryMonth": "0",
					"workYear": "5-10年",
					"jobNature": "全职",
					"education": "大专",
					"positionAdvantage": "13薪，班车，培训机会",
					"imState": "today",
					"lastLogin": "2021-04-05 13:02:09",
					"publisherId": 5104512,
					"approve": 1,
					"subwayline": None,
					"stationname": None,
					"linestaion": None,
					"latitude": "31.129465",
					"longitude": "121.535933",
					"distance": None,
					"hitags": None,
					"resumeProcessRate": 2,
					"resumeProcessDay": 1,
					"score": 19,
					"newScore": 0,
					"matchScore": 3.5964272,
					"matchScoreExplain": None,
					"query": None,
					"explain": None,
					"isSchoolJob": 0,
					"adWord": 0,
					"plus": None,
					"pcShow": 0,
					"appShow": 0,
					"deliver": 0,
					"gradeDescription": None,
					"promotionScoreExplain": None,
					"isHotHire": 0,
					"count": 0,
					"aggregatePositionIds": [],
					"reCallType": None,
					"userExpectId": -1,
					"userExpectText": "",
					"promotionType": None,
					"is51Job": False,
					"expectJobId": None,
					"encryptId": "03eb1778a7d5776d8cfc8f9e9deae5a6d5abd8ac7898c65a",
					"detailRecall": False,
					"famousCompany": False,
					"hunterJob": False
				},
				{
					"positionId": 6662212,
					"positionName": "系统运维工程师",
					"companyId": 10369,
					"companyFullName": "完美世界（北京）软件科技发展有限公司",
					"companyShortName": "完美世界",
					"companyLogo": "image1/M00/00/15/CgYXBlTUWECAXAksAABGkmdtwig327.jpg",
					"companySize": "2000人以上",
					"industryField": "游戏",
					"financeStage": "上市公司",
					"companyLabelList": [
						"绩效奖金",
						"五险一金",
						"带薪年假",
						"年度旅游"
					],
					"firstType": "开发|测试|运维类",
					"secondType": "运维",
					"thirdType": "运维工程师",
					"skillLables": [
						"运维",
						"IDC",
						"Linux",
						"Windows"
					],
					"positionLables": [
						"运维",
						"IDC",
						"Linux",
						"Windows"
					],
					"industryLables": [],
					"createTime": "2021-04-05 13:00:00",
					"formatCreateTime": "13:00发布",
					"city": "上海",
					"district": "杨浦区",
					"businessZones": None,
					"salary": "20k-30k",
					"salaryMonth": "0",
					"workYear": "3-5年",
					"jobNature": "全职",
					"education": "本科",
					"positionAdvantage": "技术大牛一对一",
					"imState": "today",
					"lastLogin": "2021-04-05 10:51:01",
					"publisherId": 9687871,
					"approve": 1,
					"subwayline": "4号线",
					"stationname": "杨树浦路",
					"linestaion": "4号线_杨树浦路",
					"latitude": "31.251924",
					"longitude": "121.532377",
					"distance": None,
					"hitags": None,
					"resumeProcessRate": 0,
					"resumeProcessDay": 0,
					"score": 19,
					"newScore": 0,
					"matchScore": 3.6036634,
					"matchScoreExplain": None,
					"query": None,
					"explain": None,
					"isSchoolJob": 0,
					"adWord": 0,
					"plus": None,
					"pcShow": 0,
					"appShow": 0,
					"deliver": 0,
					"gradeDescription": None,
					"promotionScoreExplain": None,
					"isHotHire": 0,
					"count": 0,
					"aggregatePositionIds": [],
					"reCallType": None,
					"userExpectId": -1,
					"userExpectText": "",
					"promotionType": None,
					"is51Job": False,
					"expectJobId": None,
					"encryptId": "cf84cadcf9d21e1bf2eaa774fc09d9020cef7180e38ca538",
					"detailRecall": False,
					"famousCompany": True,
					"hunterJob": False
				},
				{
					"positionId": 8031678,
					"positionName": "运维开发工程师",
					"companyId": 70721,
					"companyFullName": "北京金堤科技有限公司",
					"companyShortName": "天眼查",
					"companyLogo": "i/image/M00/6F/52/CgqCHl-1GeaAfsRFAAA5GiRJFxA742.png",
					"companySize": "500-2000人",
					"industryField": "数据服务｜咨询",
					"financeStage": "不需要融资",
					"companyLabelList": [
						"专项奖金",
						"股票期权",
						"带薪年假",
						"定期体检"
					],
					"firstType": "开发|测试|运维类",
					"secondType": "运维",
					"thirdType": "运维开发工程师",
					"skillLables": [
						"Python",
						"Linux",
						"运维开发",
						"TCP/IP协议"
					],
					"positionLables": [
						"Python",
						"Linux",
						"运维开发",
						"TCP/IP协议"
					],
					"industryLables": [],
					"createTime": "2021-04-05 13:01:03",
					"formatCreateTime": "13:01发布",
					"city": "北京",
					"district": "海淀区",
					"businessZones": [
						"知春路",
						"中关村",
						"双榆树"
					],
					"salary": "20k-40k",
					"salaryMonth": "15",
					"workYear": "3-5年",
					"jobNature": "全职",
					"education": "不限",
					"positionAdvantage": "发展前景巨大",
					"imState": "today",
					"lastLogin": "2021-04-05 13:04:45",
					"publisherId": 1707653,
					"approve": 1,
					"subwayline": "10号线",
					"stationname": "知春路",
					"linestaion": "4号线大兴线_人民大学;4号线大兴线_海淀黄庄;10号线_海淀黄庄;10号线_知春里;10号线_知春路;13号线_知春路",
					"latitude": "39.977084",
					"longitude": "116.331999",
					"distance": None,
					"hitags": [
						"免费下午茶",
						"免费体检",
						"地铁周边",
						"5险1金",
						"工作居住证"
					],
					"resumeProcessRate": 5,
					"resumeProcessDay": 0,
					"score": 19,
					"newScore": 0,
					"matchScore": 3.6000454,
					"matchScoreExplain": None,
					"query": None,
					"explain": None,
					"isSchoolJob": 0,
					"adWord": 0,
					"plus": None,
					"pcShow": 0,
					"appShow": 0,
					"deliver": 0,
					"gradeDescription": None,
					"promotionScoreExplain": None,
					"isHotHire": 0,
					"count": 0,
					"aggregatePositionIds": [],
					"reCallType": None,
					"userExpectId": -1,
					"userExpectText": "",
					"promotionType": None,
					"is51Job": False,
					"expectJobId": None,
					"encryptId": "03d9671926b16e909bac7820031dccf3e1962f371511162e",
					"detailRecall": False,
					"famousCompany": True,
					"hunterJob": False
				}
			],
			"locationInfo": {
				"city": None,
				"district": None,
				"businessZone": None,
				"isAllhotBusinessZone": False,
				"locationCode": None,
				"queryByGisCode": False
			},
			"queryAnalysisInfo": {
				"positionName": "运维工程师",
				"positionNames": [
					"运维工程师"
				],
				"companyName": None,
				"industryName": None,
				"usefulCompany": False,
				"jobNature": None
			},
			"strategyProperty": {
				"name": "dm-csearch-personalPositionLayeredStrategyNew",
				"id": 0
			},
			"hotLabels": None,
			"hiTags": None,
			"benefitTags": None,
			"industryField": None,
			"companySize": None,
			"positionName": None,
			"totalCount": 3984,
			"triggerOrSearch": False,
			"categoryTypeAndName": {
				"3": "运维工程师"
			}
		},
		"pageSize": 15
	},
	"resubmitToken": None,
	"requestId": None
}
#print(dict1['content']['positionResult']['result'][0]['positionName'])
# 豆瓣电影
dict2={
  "subjects": [
    {
      "episodes_info": "",
      "rate": "6.6",
      "cover_x": 2764,
      "title": "哥斯拉大战金刚",
      "url": "https:\/\/movie.douban.com\/subject\/26613692\/",
      "playable": False,
      "cover": "https://img9.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2634253484.jpg",
      "id": "26613692",
      "cover_y": 4096,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "8.9",
      "cover_x": 2025,
      "title": "扎克·施奈德版正义联盟",
      "url": "https:\/\/movie.douban.com\/subject\/35076714\/",
      "playable": False,
      "cover": "https://img9.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2634360594.jpg",
      "id": "35076714",
      "cover_y": 3000,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "6.1",
      "cover_x": 1049,
      "title": "腿",
      "url": "https:\/\/movie.douban.com\/subject\/34925598\/",
      "playable": False,
      "cover": "https://img1.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2621401958.jpg",
      "id": "34925598",
      "cover_y": 1498,
      "is_new": True
    },
    {
      "episodes_info": "",
      "rate": "6.1",
      "cover_x": 1000,
      "title": "地牢女孩",
      "url": "https:\/\/movie.douban.com\/subject\/35324548\/",
      "playable": False,
      "cover": "https://img3.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2634312670.jpg",
      "id": "35324548",
      "cover_y": 1500,
      "is_new": True
    },
    {
      "episodes_info": "",
      "rate": "6.7",
      "cover_x": 1772,
      "title": "育蝇奇谭",
      "url": "https:\/\/movie.douban.com\/subject\/33459135\/",
      "playable": False,
      "cover": "https://img1.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2622317489.jpg",
      "id": "33459135",
      "cover_y": 2363,
      "is_new": True
    },
    {
      "episodes_info": "",
      "rate": "5.7",
      "cover_x": 3571,
      "title": "侍神令",
      "url": "https:\/\/movie.douban.com\/subject\/26935283\/",
      "playable": True,
      "cover": "https://img2.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2629260713.jpg",
      "id": "26935283",
      "cover_y": 4990,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "8.3",
      "cover_x": 1200,
      "title": "浅田家！",
      "url": "https:\/\/movie.douban.com\/subject\/26958479\/",
      "playable": False,
      "cover": "https://img1.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2614188527.jpg",
      "id": "26958479",
      "cover_y": 1698,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "8.3",
      "cover_x": 2700,
      "title": "无依之地",
      "url": "https:\/\/movie.douban.com\/subject\/30458949\/",
      "playable": False,
      "cover": "https://img1.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2630453887.jpg",
      "id": "30458949",
      "cover_y": 4000,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "7.0",
      "cover_x": 810,
      "title": "沿路而下",
      "url": "https:\/\/movie.douban.com\/subject\/30456637\/",
      "playable": False,
      "cover": "https://img1.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2633150167.jpg",
      "id": "30456637",
      "cover_y": 1200,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "7.4",
      "cover_x": 1313,
      "title": "倒霉性爱，发狂黄片",
      "url": "https:\/\/movie.douban.com\/subject\/35242942\/",
      "playable": False,
      "cover": "https://img3.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2638021971.jpg",
      "id": "35242942",
      "cover_y": 1875,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "7.9",
      "cover_x": 992,
      "title": "同学麦娜丝",
      "url": "https:\/\/movie.douban.com\/subject\/34902639\/",
      "playable": False,
      "cover": "https://img2.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2623673142.jpg",
      "id": "34902639",
      "cover_y": 1418,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "8.7",
      "cover_x": 1200,
      "title": "命运之夜——天之杯Ⅲ：春之歌",
      "url": "https:\/\/movie.douban.com\/subject\/26759820\/",
      "playable": False,
      "cover": "https://img1.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2586167249.jpg",
      "id": "26759820",
      "cover_y": 1714,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "7.2",
      "cover_x": 4950,
      "title": "寻龙传说",
      "url": "https:\/\/movie.douban.com\/subject\/34804147\/",
      "playable": False,
      "cover": "https://img9.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2633531206.jpg",
      "id": "34804147",
      "cover_y": 6900,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "6.7",
      "cover_x": 5000,
      "title": "许愿神龙",
      "url": "https:\/\/movie.douban.com\/subject\/27662747\/",
      "playable": True,
      "cover": "https://img1.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2626260539.jpg",
      "id": "27662747",
      "cover_y": 7053,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "8.5",
      "cover_x": 2025,
      "title": "亲爱的同志",
      "url": "https:\/\/movie.douban.com\/subject\/34960094\/",
      "playable": False,
      "cover": "https://img1.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2630627669.jpg",
      "id": "34960094",
      "cover_y": 3000,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "8.0",
      "cover_x": 2067,
      "title": "孤味",
      "url": "https:\/\/movie.douban.com\/subject\/34805873\/",
      "playable": False,
      "cover": "https://img3.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2623646280.jpg",
      "id": "34805873",
      "cover_y": 2953,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "8.2",
      "cover_x": 5000,
      "title": "打开心世界",
      "url": "https:\/\/movie.douban.com\/subject\/30454679\/",
      "playable": False,
      "cover": "https://img3.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2632936000.jpg",
      "id": "30454679",
      "cover_y": 7071,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "8.6",
      "cover_x": 1500,
      "title": "芝加哥七君子审判",
      "url": "https:\/\/movie.douban.com\/subject\/2609258\/",
      "playable": False,
      "cover": "https://img3.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2620161520.jpg",
      "id": "2609258",
      "cover_y": 2222,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "8.8",
      "cover_x": 6611,
      "title": "心灵奇旅",
      "url": "https:\/\/movie.douban.com\/subject\/24733428\/",
      "playable": True,
      "cover": "https://img9.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2626308994.jpg",
      "id": "24733428",
      "cover_y": 9435,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "7.4",
      "cover_x": 3264,
      "title": "送你一朵小红花",
      "url": "https:\/\/movie.douban.com\/subject\/35096844\/",
      "playable": True,
      "cover": "https://img1.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2618247457.jpg",
      "id": "35096844",
      "cover_y": 4929,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "7.9",
      "cover_x": 6198,
      "title": "吉祥如意",
      "url": "https:\/\/movie.douban.com\/subject\/35068230\/",
      "playable": True,
      "cover": "https://img3.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2632185061.jpg",
      "id": "35068230",
      "cover_y": 8685,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "6.0",
      "cover_x": 1656,
      "title": "发财日记",
      "url": "https:\/\/movie.douban.com\/subject\/27594653\/",
      "playable": True,
      "cover": "https://img3.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2632091530.jpg",
      "id": "27594653",
      "cover_y": 2500,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "7.5",
      "cover_x": 1000,
      "title": "酒精计划",
      "url": "https:\/\/movie.douban.com\/subject\/30323120\/",
      "playable": False,
      "cover": "https://img9.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2628440526.jpg",
      "id": "30323120",
      "cover_y": 1481,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "6.2",
      "cover_x": 2764,
      "title": "神奇女侠1984",
      "url": "https:\/\/movie.douban.com\/subject\/27073752\/",
      "playable": True,
      "cover": "https://img1.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2626959989.jpg",
      "id": "27073752",
      "cover_y": 4096,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "7.0",
      "cover_x": 2622,
      "title": "缉魂",
      "url": "https:\/\/movie.douban.com\/subject\/34962956\/",
      "playable": True,
      "cover": "https://img3.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2629413230.jpg",
      "id": "34962956",
      "cover_y": 3721,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "7.7",
      "cover_x": 2160,
      "title": "信条",
      "url": "https:\/\/movie.douban.com\/subject\/30444960\/",
      "playable": True,
      "cover": "https://img9.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2618403186.jpg",
      "id": "30444960",
      "cover_y": 3201,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "7.6",
      "cover_x": 1500,
      "title": "女生要革命",
      "url": "https:\/\/movie.douban.com\/subject\/30465068\/",
      "playable": False,
      "cover": "https://img2.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2632592932.jpg",
      "id": "30465068",
      "cover_y": 2222,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "7.7",
      "cover_x": 1500,
      "title": "女人的碎片",
      "url": "https:\/\/movie.douban.com\/subject\/34869387\/",
      "playable": False,
      "cover": "https://img1.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2625877469.jpg",
      "id": "34869387",
      "cover_y": 2222,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "7.8",
      "cover_x": 2805,
      "title": "一秒钟",
      "url": "https:\/\/movie.douban.com\/subject\/30257787\/",
      "playable": True,
      "cover": "https://img1.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2628373757.jpg",
      "id": "30257787",
      "cover_y": 4134,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "7.9",
      "cover_x": 1080,
      "title": "疯狂原始人2",
      "url": "https:\/\/movie.douban.com\/subject\/24298954\/",
      "playable": True,
      "cover": "https://img9.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2624607255.jpg",
      "id": "24298954",
      "cover_y": 1600,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "8.4",
      "cover_x": 1449,
      "title": "鬼灭之刃 剧场版 无限列车篇",
      "url": "https:\/\/movie.douban.com\/subject\/34845781\/",
      "playable": False,
      "cover": "https://img3.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2595123270.jpg",
      "id": "34845781",
      "cover_y": 2048,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "7.7",
      "cover_x": 674,
      "title": "无声",
      "url": "https:\/\/movie.douban.com\/subject\/34850598\/",
      "playable": False,
      "cover": "https://img2.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2619399682.jpg",
      "id": "34850598",
      "cover_y": 960,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "5.4",
      "cover_x": 4000,
      "title": "猫和老鼠",
      "url": "https:\/\/movie.douban.com\/subject\/3439312\/",
      "playable": False,
      "cover": "https://img3.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2632043260.jpg",
      "id": "3439312",
      "cover_y": 5823,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "7.6",
      "cover_x": 1429,
      "title": "拆弹专家2",
      "url": "https:\/\/movie.douban.com\/subject\/30171424\/",
      "playable": True,
      "cover": "https://img3.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2621379901.jpg",
      "id": "30171424",
      "cover_y": 2000,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "8.0",
      "cover_x": 8100,
      "title": "玫瑰岛的不可思议的历史",
      "url": "https:\/\/movie.douban.com\/subject\/34982759\/",
      "playable": False,
      "cover": "https://img9.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2624341545.jpg",
      "id": "34982759",
      "cover_y": 12000,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "6.6",
      "cover_x": 2000,
      "title": "谢里",
      "url": "https:\/\/movie.douban.com\/subject\/30310219\/",
      "playable": False,
      "cover": "https://img9.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2630607784.jpg",
      "id": "30310219",
      "cover_y": 3000,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "7.5",
      "cover_x": 1500,
      "title": "白虎",
      "url": "https:\/\/movie.douban.com\/subject\/34983332\/",
      "playable": False,
      "cover": "https://img9.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2631140996.jpg",
      "id": "34983332",
      "cover_y": 2222,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "7.2",
      "cover_x": 2764,
      "title": "犹大与黑弥赛亚",
      "url": "https:\/\/movie.douban.com\/subject\/30464264\/",
      "playable": False,
      "cover": "https://img3.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2620539710.jpg",
      "id": "30464264",
      "cover_y": 4096,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "7.5",
      "cover_x": 579,
      "title": "较量2",
      "url": "https:\/\/movie.douban.com\/subject\/35310153\/",
      "playable": False,
      "cover": "https://img3.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2633604200.jpg",
      "id": "35310153",
      "cover_y": 873,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "7.3",
      "cover_x": 4000,
      "title": "夺冠",
      "url": "https:\/\/movie.douban.com\/subject\/30128916\/",
      "playable": True,
      "cover": "https://img2.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2620083313.jpg",
      "id": "30128916",
      "cover_y": 5587,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "7.8",
      "cover_x": 1013,
      "title": "发掘",
      "url": "https:\/\/movie.douban.com\/subject\/25862300\/",
      "playable": False,
      "cover": "https://img3.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2627529751.jpg",
      "id": "25862300",
      "cover_y": 1500,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "7.3",
      "cover_x": 1984,
      "title": "里夫金的电影节",
      "url": "https:\/\/movie.douban.com\/subject\/30353869\/",
      "playable": False,
      "cover": "https://img2.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2619170443.jpg",
      "id": "30353869",
      "cover_y": 2835,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "7.4",
      "cover_x": 1500,
      "title": "曼克",
      "url": "https:\/\/movie.douban.com\/subject\/34461705\/",
      "playable": False,
      "cover": "https://img9.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2623412955.jpg",
      "id": "34461705",
      "cover_y": 2222,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "6.1",
      "cover_x": 3000,
      "title": "紧急救援",
      "url": "https:\/\/movie.douban.com\/subject\/26342391\/",
      "playable": True,
      "cover": "https://img9.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2627025706.jpg",
      "id": "26342391",
      "cover_y": 4200,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "7.3",
      "cover_x": 640,
      "title": "无声",
      "url": "https:\/\/movie.douban.com\/subject\/33591810\/",
      "playable": False,
      "cover": "https://img1.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2621016058.jpg",
      "id": "33591810",
      "cover_y": 915,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "7.5",
      "cover_x": 673,
      "title": "亲爱的房客",
      "url": "https:\/\/movie.douban.com\/subject\/35069520\/",
      "playable": False,
      "cover": "https://img1.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2617989427.jpg",
      "id": "35069520",
      "cover_y": 960,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "7.6",
      "cover_x": 2000,
      "title": "八佰",
      "url": "https:\/\/movie.douban.com\/subject\/26754233\/",
      "playable": True,
      "cover": "https://img9.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2615992304.jpg",
      "id": "26754233",
      "cover_y": 2800,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "6.3",
      "cover_x": 1500,
      "title": "我很在乎",
      "url": "https:\/\/movie.douban.com\/subject\/30482481\/",
      "playable": False,
      "cover": "https://img3.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2630607691.jpg",
      "id": "30482481",
      "cover_y": 2222,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "7.2",
      "cover_x": 848,
      "title": "海边的异邦人",
      "url": "https:\/\/movie.douban.com\/subject\/34869495\/",
      "playable": False,
      "cover": "https://img3.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2616484920.jpg",
      "id": "34869495",
      "cover_y": 1200,
      "is_new": False
    },
    {
      "episodes_info": "",
      "rate": "7.6",
      "cover_x": 1500,
      "title": "电话",
      "url": "https:\/\/movie.douban.com\/subject\/30346025\/",
      "playable": False,
      "cover": "https://img1.doubanio.com\/view\/photo\/s_ratio_poster\/public\/p2625879789.jpg",
      "id": "30346025",
      "cover_y": 2172,
      "is_new": False
    }
  ]
}
# print(dict2['subjects'][0]['rate'])
# for i in dict2['subjects']:
# 	for key,value in i.items():
# 		if 'rate' in i:
# 			if key=='rate':
# 				 print(value)
# 				 print(int(value.split('.')[0]))
#
# dict4={'name':'hxj','age':18}
#
# dict_list=list(dict4.keys())
# print(dict_list)
# list_dict=dict(enumerate(dict_list))
# print(list_dict)

#文件的路径以及及具体的文件，模式，编码
open('log.txt')
#默认参数可以不传参数
#def open(file, mode='r', buffering=None, encoding=None, errors=None, newline=None, closefd=True):
#非默认参拜在前面 默认参数在后面
#def add(a,b=3):
def login(username='admin',password='admin'):
	pass

def data_dir(filePath='d:/data',filename=None):
	print(filePath)
	print(filename)

data_dir(filename='text.txt')
#位置参数要一一对应
